version: '3.8'

services:
  karma-kruhlyk:
    image: webyhomelab/karma-community-app:latest
    container_name: karma-kruhlyk
    restart: unless-stopped
    ports:
      - "127.0.0.1:3016:3000"
    environment:
      - DB_PATH=/app/backend/data/karma.db
      - BOT_TOKEN=DUMMY_TOKEN
    volumes:
      - ./data/kruhlyk:/app/backend/data

  karma-symyrenka:
    image: webyhomelab/karma-community-app:latest
    container_name: karma-symyrenka
    restart: unless-stopped
    ports:
      - "127.0.0.1:3017:3000"
    environment:
      - DB_PATH=/app/backend/data/karma.db
      - BOT_TOKEN=DUMMY_TOKEN
    volumes:
      - ./data/symyrenka:/app/backend/data

  karma-kruhlyk2:
    image: webyhomelab/karma-community-app:latest
    container_name: karma-kruhlyk2
    restart: unless-stopped
    ports:
      - "127.0.0.1:3019:3000"
    environment:
      - DB_PATH=/app/backend/data/karma.db
      - BOT_TOKEN=DUMMY_TOKEN
    volumes:
      - ./data/kruhlyk2:/app/backend/data
