version: '3.8'

services:
  karma-symyrenka:
    image: webyhomelab/karma-community-app:latest
    container_name: karma-symyrenka
    restart: unless-stopped
    ports:
      - "127.0.0.1:3017:3000"
    environment:
      - DB_PATH=/app/backend/data/karma.db
      - BOT_TOKEN=DUMMY_TOKEN
    volumes:
      - ./data/symyrenka:/app/backend/data
